import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { timingSafeEqual } from 'crypto';
import { jwtVerify } from 'jose';

/**
 * Verify admin access using either:
 * 1. JWT token (generated by /api/admin/generate-token, 1 hour expiration)
 * 2. Legacy admin secret token (for backward compatibility, no expiration)
 */
async function verifyAdminAccess(request: NextRequest): Promise<boolean> {
  const adminToken = request.headers.get('X-Admin-Token');
  const bearerAuth = request.headers.get('Authorization');
  const expectedToken = process.env.ADMIN_SECRET_TOKEN;

  if (!adminToken && !bearerAuth) {
    console.warn('[SECURITY] Admin token missing');
    return false;
  }

  // Method 1: Verify JWT token (preferred, has expiration)
  if (bearerAuth?.startsWith('Bearer ')) {
    const jwtToken = bearerAuth.slice('Bearer '.length);
    const jwtSecret = process.env.SUPABASE_JWT_SECRET;

    if (jwtSecret) {
      try {
        const secret = new TextEncoder().encode(jwtSecret);
        const verified = await jwtVerify(jwtToken, secret);

        // Check if token has admin role claim
        if (verified.payload.role === 'admin' || verified.payload.sub === 'admin') {
          console.log('[ADMIN] JWT token verified');
          return true;
        }
      } catch (error) {
        console.warn('[SECURITY] JWT verification failed:', error instanceof Error ? error.message : 'Unknown error');
      }
    }
  }

  // Method 2: Legacy admin secret token (no expiration, less secure)
  if (adminToken && expectedToken) {
    let isValid = false;
    try {
      isValid = timingSafeEqual(
        Buffer.from(adminToken),
        Buffer.from(expectedToken)
      );
    } catch {
      isValid = false;
    }

    if (isValid) {
      console.warn('[SECURITY] Using legacy admin token - consider rotating to JWT via /api/admin/generate-token');
      return true;
    }
  }

  console.warn('[SECURITY] Invalid admin credential attempt', {
    ipAddress: request.headers.get('x-forwarded-for'),
    timestamp: new Date().toISOString()
  });

  return false;
}

export async function DELETE(request: NextRequest) {
  try {
    // Verificar acceso de admin
    const isAdminAuthorized = await verifyAdminAccess(request);
    if (!isAdminAuthorized) {
      console.warn('[SECURITY] Unauthorized database wipe attempt');
      return NextResponse.json(
        { error: 'No autorizado. Acceso de administrador requerido.', success: false },
        { status: 403 }
      );
    }

    // SAFEGUARD 1: Require explicit confirmation header
    const confirmationToken = request.headers.get('X-Confirm-Wipe');
    const expectedConfirmation = process.env.DATABASE_WIPE_CONFIRMATION_TOKEN;

    if (!confirmationToken || !expectedConfirmation) {
      console.warn('[SECURITY] Database wipe confirmation missing');
      return NextResponse.json(
        {
          error: 'Confirmación requerida. Incluye header X-Confirm-Wipe con token de confirmación.',
          success: false
        },
        { status: 400 }
      );
    }

    // Timing-safe confirmation comparison
    if (!timingSafeEqual(Buffer.from(confirmationToken), Buffer.from(expectedConfirmation))) {
      console.warn('[SECURITY] Invalid database wipe confirmation attempt', {
        ipAddress: request.headers.get('x-forwarded-for'),
        timestamp: new Date().toISOString()
      });
      return NextResponse.json(
        { error: 'Token de confirmación inválido', success: false },
        { status: 403 }
      );
    }

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

    if (!supabaseUrl || !supabaseServiceKey) {
      return NextResponse.json(
        { error: 'Configuración faltante', success: false },
        { status: 500 }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // SAFEGUARD 2: Log detailed audit trail BEFORE deletion
    const timestamp = new Date().toISOString();
    const adminUser = request.headers.get('X-Admin-Email') || 'unknown';
    const ipAddress = request.headers.get('x-forwarded-for') || 'unknown';

    console.warn('[CRITICAL] Database wipe operation initiated', {
      timestamp,
      admin: adminUser,
      ipAddress,
      action: 'DELETE_ALL_CANDIDATES_AND_VACANTES'
    });

    // Delete all candidates first
    const { error: candidatosError, count: candidatosCount } = await supabase
      .from('candidatos')
      .delete()
      .neq('id', 'null')
      .select('id', { count: 'exact', head: true });

    if (candidatosError) {
      console.error('[API] Error deleting all candidates:', candidatosError);
      return NextResponse.json(
        { error: 'Error al eliminar candidatos', success: false },
        { status: 500 }
      );
    }

    // Delete all vacantes
    const { error: vacantesError, count: vacantesCount } = await supabase
      .from('vacantes')
      .delete()
      .neq('id', 'null')
      .select('id', { count: 'exact', head: true });

    if (vacantesError) {
      console.error('[API] Error deleting all vacantes:', vacantesError);
      return NextResponse.json(
        { error: 'Error al limpiar vacantes', success: false },
        { status: 500 }
      );
    }

    // SAFEGUARD 3: Log detailed completion audit trail
    console.warn('[CRITICAL] Database wipe operation completed successfully', {
      timestamp: new Date().toISOString(),
      admin: adminUser,
      ipAddress,
      candidatosDeleted: candidatosCount || 0,
      vacantesDeleted: vacantesCount || 0,
      action: 'DELETE_ALL_COMPLETED'
    });

    return NextResponse.json({
      success: true,
      message: 'Base de datos limpiada correctamente',
      deletedCandidates: candidatosCount || 0,
      deletedVacantes: vacantesCount || 0,
      timestamp
    });
  } catch (error) {
    console.error('[API] Error in database wipe operation:', error);
    return NextResponse.json(
      { error: 'Error del servidor', success: false },
      { status: 500 }
    );
  }
}
