import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { timingSafeEqual } from 'crypto';
import { jwtVerify } from 'jose';

/**
 * Verify admin access using either:
 * 1. JWT token (generated by /api/admin/generate-token, 1 hour expiration)
 * 2. Legacy admin secret token (for backward compatibility, no expiration)
 */
async function verifyAdminAccess(request: NextRequest): Promise<boolean> {
  const adminToken = request.headers.get('X-Admin-Token');
  const bearerAuth = request.headers.get('Authorization');
  const expectedToken = process.env.ADMIN_SECRET_TOKEN;

  if (!adminToken && !bearerAuth) {
    console.warn('[SECURITY] Admin token missing');
    return false;
  }

  // Method 1: Verify JWT token (preferred, has expiration)
  if (bearerAuth?.startsWith('Bearer ')) {
    const jwtToken = bearerAuth.slice('Bearer '.length);
    const jwtSecret = process.env.SUPABASE_JWT_SECRET;

    if (jwtSecret) {
      try {
        const secret = new TextEncoder().encode(jwtSecret);
        const verified = await jwtVerify(jwtToken, secret);

        // Check if token has admin role claim
        if (verified.payload.role === 'admin' || verified.payload.sub === 'admin') {
          console.log('[ADMIN] JWT token verified');
          return true;
        }
      } catch (error) {
        console.warn('[SECURITY] JWT verification failed:', error instanceof Error ? error.message : 'Unknown error');
      }
    }
  }

  // Method 2: Legacy admin secret token (no expiration, less secure)
  if (adminToken && expectedToken) {
    let isValid = false;
    try {
      isValid = timingSafeEqual(
        Buffer.from(adminToken),
        Buffer.from(expectedToken)
      );
    } catch {
      isValid = false;
    }

    if (isValid) {
      console.warn('[SECURITY] Using legacy admin token - consider rotating to JWT via /api/admin/generate-token');
      return true;
    }
  }

  console.warn('[SECURITY] Invalid admin credential attempt', {
    ipAddress: request.headers.get('x-forwarded-for'),
    timestamp: new Date().toISOString()
  });

  return false;
}

export async function DELETE(request: NextRequest) {
  try {
    // Verificar acceso de admin
    const isAdminAuthorized = await verifyAdminAccess(request);
    if (!isAdminAuthorized) {
      return NextResponse.json(
        { error: 'No autorizado. Acceso de administrador requerido.', success: false },
        { status: 403 }
      );
    }

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

    if (!supabaseUrl || !supabaseServiceKey) {
      return NextResponse.json(
        { error: 'Configuración faltante', success: false },
        { status: 500 }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Delete all candidates first
    const { error: candidatosError } = await supabase
      .from('candidatos')
      .delete()
      .neq('id', 'null');

    if (candidatosError) {
      console.error('[API] Error deleting all candidates:', candidatosError);
    }

    // Delete all vacantes
    const { error: vacantesError } = await supabase
      .from('vacantes')
      .delete()
      .neq('id', 'null');

    if (vacantesError) {
      console.error('[API] Error deleting all vacantes:', vacantesError);
      return NextResponse.json(
        { error: 'Error al limpiar vacantes', success: false },
        { status: 500 }
      );
    }

    console.log('[API] Base de datos limpiada');
    return NextResponse.json({
      success: true,
      message: 'Base de datos limpiada correctamente',
    });
  } catch (error) {
    console.error('[API] Error:', error);
    return NextResponse.json(
      { error: 'Error del servidor', success: false },
      { status: 500 }
    );
  }
}
