export const mockCandidates = [
  {
    id: 'mock-1',
    nombre: 'Víctor Barillas',
    email: 'victor.barillas@gmail.com',
    telefono: '+502 7123 4567',
    score_ia: 93,
    estado: 'precalificado',
    cv_url: '/uploads/victor-barillas.pdf',
    vacante_id: 'demo-1',
    habilidades: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Docker'],
    experiencia_anos: 6,
    educacion: 'Ingeniería en Sistemas - Universidad de San Carlos',
    feedback_ia: 'Candidato excelente con experiencia completa en stack solicitado. Muy fuerte en backend y DevOps.',
    resumen_ejecutivo: 'Desarrollador Full Stack Senior con 6 años de experiencia. Especializado en arquitecturas escalables y transformación digital.',
    video_url: 'https://example.com/video1.mp4',
    transcripcion: 'Me llamo Víctor, tengo 6 años de experiencia en desarrollo full stack. He trabajado en empresas como XYZ donde lideré proyectos de 5+ personas. Soy experto en React, Node.js y DevOps con Docker y Kubernetes.',
    puntuaciones: {
      tecnico: 95,
      comunicacion: 88,
      liderazgo: 85,
      resolucion_problemas: 92,
      cultura_empresa: 90,
    },
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-2',
    nombre: 'Sofía Morales',
    email: 'sofia.morales@gmail.com',
    telefono: '+502 7234 5678',
    score_ia: 87,
    estado: 'precalificado',
    cv_url: '/uploads/sofia-morales.pdf',
    vacante_id: 'demo-1',
    habilidades: ['React', 'JavaScript', 'CSS', 'UI/UX', 'Figma'],
    experiencia_anos: 4,
    educacion: 'Diseño Gráfico con especialización en UX - UNIS',
    feedback_ia: 'Candidata con sólida experiencia en frontend. Excelente atención al detalle y conocimientos de UX/UI que complementan sus habilidades de desarrollo.',
    resumen_ejecutivo: 'Desarrolladora Frontend con 4 años de experiencia y formación en UX/UI. Apasionada por crear interfaces intuitivas y responsivas.',
    video_url: 'https://example.com/video2.mp4',
    transcripcion: 'Hola, soy Sofía. Tengo 4 años de experiencia como desarrolladora frontend especializada en React. También tengo formación en UX/UI lo que me permite crear interfaces hermosas y funcionales.',
    puntuaciones: {
      tecnico: 88,
      comunicacion: 92,
      liderazgo: 72,
      resolucion_problemas: 85,
      cultura_empresa: 88,
    },
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-3',
    nombre: 'Carlos Méndez',
    email: 'carlos.mendez@gmail.com',
    telefono: '+502 7345 6789',
    score_ia: 84,
    estado: 'evaluacion',
    cv_url: '/uploads/carlos-mendez.pdf',
    vacante_id: 'demo-1',
    habilidades: ['Python', 'FastAPI', 'PostgreSQL', 'GraphQL', 'Jest'],
    experiencia_anos: 5,
    educacion: 'Licenciatura en Informática - URL',
    feedback_ia: 'Candidato con buena base técnica. Experiencia en backend moderno con Python. Necesita mejorar habilidades de comunicación pero tiene potencial alto.',
    resumen_ejecutivo: 'Desarrollador Backend Senior con 5 años de experiencia. Especializado en APIs REST y GraphQL con énfasis en performance.',
    video_url: 'https://example.com/video3.mp4',
    transcripcion: 'Mi nombre es Carlos y tengo 5 años desarrollando en Python con FastAPI. He optimizado bases de datos para aplicaciones de alto tráfico y creado APIs escalables.',
    puntuaciones: {
      tecnico: 91,
      comunicacion: 78,
      liderazgo: 75,
      resolucion_problemas: 89,
      cultura_empresa: 82,
    },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-4',
    nombre: 'Andrea López',
    email: 'andrea.lopez@gmail.com',
    telefono: '+502 7456 7890',
    score_ia: 89,
    estado: 'precalificado',
    cv_url: '/uploads/andrea-lopez.pdf',
    vacante_id: 'demo-2',
    habilidades: ['Ventas', 'CRM', 'Negociación', 'Gestión de Clientes', 'Excel'],
    experiencia_anos: 7,
    educacion: 'Administración de Empresas - USAC',
    feedback_ia: 'Candidata con excelente trayectoria en ventas B2B. Demuestra sólidas habilidades de negociación y cierre de deals. Alto potencial de liderazgo.',
    resumen_ejecutivo: 'Ejecutiva de Ventas Senior con 7 años de experiencia en sector tech. Especializada en ventas B2B con track record de cierre de 150%+ de cuota anual.',
    video_url: 'https://example.com/video4.mp4',
    transcripcion: 'Hola, soy Andrea. Tengo 7 años en ventas, principalmente en tech. He cerrado deals de más de $500k y liderado equipos de 4 personas. Mis clientes son empresas Fortune 500.',
    puntuaciones: {
      tecnico: 75,
      comunicacion: 95,
      liderazgo: 88,
      resolucion_problemas: 86,
      cultura_empresa: 90,
    },
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-5',
    nombre: 'David González',
    email: 'david.gonzalez@gmail.com',
    telefono: '+502 7567 8901',
    score_ia: 82,
    estado: 'precalificado',
    cv_url: '/uploads/david-gonzalez.pdf',
    vacante_id: 'demo-2',
    habilidades: ['Ventas', 'Prospección', 'Telemarketing', 'CRM Salesforce', 'Reportes'],
    experiencia_anos: 3,
    educacion: 'Técnico en Comercialización - ISA',
    feedback_ia: 'Candidato con buenos fundamentos en ventas. Necesita desarrollo en soft skills pero tiene fuerte capacidad de prospección y seguimiento.',
    resumen_ejecutivo: 'Ejecutivo de Ventas Junior con 3 años de experiencia. Especializado en prospección y generación de leads para software.',
    video_url: 'https://example.com/video5.mp4',
    transcripcion: 'Me llamo David y tengo 3 años en ventas de software. He generado más de 200 leads calificados este año y tengo excelente tasa de conversión en cold calling.',
    puntuaciones: {
      tecnico: 72,
      comunicacion: 82,
      liderazgo: 65,
      resolucion_problemas: 78,
      cultura_empresa: 85,
    },
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockVacantes = [
  {
    id: 'demo-1',
    titulo: 'Desarrollador Full Stack Senior',
    descripcion: 'Buscamos un desarrollador Full Stack Senior con experiencia en React, Node.js y PostgreSQL. Será responsable de liderar proyectos de transformación digital.',
    requisitos: 'React, Node.js, PostgreSQL, TypeScript, Docker',
    salario_min: 3500,
    salario_max: 5500,
    ubicacion: 'Guatemala, Ciudad de Guatemala',
    tipo_contrato: 'Tiempo Completo',
    estado: 'activa',
    slug: 'desarrollador-full-stack',
    usuario_id: 'demo-user-1',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-2',
    titulo: 'Ejecutivo de Ventas B2B',
    descripcion: 'Buscamos un Ejecutivo de Ventas B2B con experiencia en cierre de deals complejos. Liderarás la expansión comercial en el segmento enterprise.',
    requisitos: 'Ventas B2B, Negociación, CRM, Gestión de Clientes',
    salario_min: 2500,
    salario_max: 4500,
    ubicacion: 'Guatemala, Ciudad de Guatemala',
    tipo_contrato: 'Tiempo Completo',
    estado: 'activa',
    slug: 'ejecutivo-ventas-b2b',
    usuario_id: 'demo-user-1',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockVacante = mockVacantes[0];

export const mockUsuario = {
  id: 'demo-user-1',
  email: 'demo@shortlist.gt',
  nombre_completo: 'Demo Reclutador',
  empresa: 'SHORTLIST.GT Demo',
  telefono: '+502 1234 5678',
};

export const mockDashboardData = {
  vacante: mockVacante,
  candidatos: mockCandidates,
  usuario: mockUsuario,
  estadisticas: {
    total_candidatos: mockCandidates.length,
    precalificados: mockCandidates.filter(c => c.estado === 'precalificado').length,
    en_evaluacion: mockCandidates.filter(c => c.estado === 'evaluacion').length,
    promedio_score: Math.round(
      mockCandidates.reduce((sum, c) => sum + c.score_ia, 0) / mockCandidates.length
    ),
  },
};
